### PR TITLE
Fix form layout on contribute page, and in popover

### PR DESCRIPTION
**Pull request by schalkneethling**
As the form on the contribute page can potentially be viewed on tablet and mobile devices it needs to be responsive all the way down to mobile. Currently there was a few issues

## Issue 1

screen shot 2018-09-21 at 19 53 37

## Issue 2

screen shot 2018-09-21 at 19 53 47

I have resolved these and it is now responsive down to mobile viewports. I have also fixed some responsive problems with the firm when in a popover. At smaller viewports the form elements would stack, and some of the copy wrapped to additional lines. This caused the button to be pushed out of view, and scrolling was not enabled.

At these viewports, the dino head also obscured the pay button, and prevented a user from clicking it. This is now also resolved.

### CODE REVIEW

**Comment by jwhitlock** [comment]
This change breaks popup collapse at 900px width

**Comment by schalkneethling** [comment]
@jwhitlock 	Let me take a look

**Comment by schalkneethling** [comment]
@jwhitlock 	fixed and updated.

**Review by jwhitlock — APPROVED** [review]
Thanks @schalkneethling, this makes the popup work better at 800 - 1100 px

**Pull request merged**
